### PR TITLE
HSEARCH-2996 Upgrade Elasticsearch dependencies to 5.6.6

### PR DESCRIPTION
**Pull request by frekele**
HSEARCH-2996 - Upgrade Elasticsearch dependencies to 5.6.6

https://hibernate.atlassian.net/browse/HSEARCH-2996

https://github.com/hibernate/hibernate-search/pull/1617

### CODE REVIEW

**Comment by frekele** [comment]
@Sanne 

When running the integration testicles we get the following error:
java.lang.NoClassDefFoundError: javax/net/ssl/SSLContext

I can not identify if the problem is in hibernate search, or in elasticsearch-client.
Maybe the error is in this line:
https://github.com/elastic/elasticsearch/blob/5.6/client/rest/src/main/java/org/elasticsearch/client/RestClientBuilder.java#L204

What do you think?

**Comment by Sanne** [comment]
Having a `java.lang.NoClassDefFoundError` it's unlikey to be an error in the client; more likely to be caused by some previous errors? Are you running this in a container?

**Comment by frekele** [comment]
I did not run local tests for this component, I just updated pom.xml directly from github, and looked at the Travis CI logs.
https://travis-ci.org/hibernate/elasticsearch-client-jbossmodules/builds/332435111

But I locally tested the hibernate-search version 5.8.2.Final and manually upgraded the elasticsearch 5.6.6 inside the wildfly.

And the same error occurred. java.lang.NoClassDefFoundError

When returning to elasticsearch v5.6.5 it recompiled normally.

Locally I'm running into  windows 10 x64 environment without container. 
jdk1.8.0_162

**Comment by Sanne** [comment]
thanks, I understand now. You're right about that line: it's causing the module to need new dependencies declared in its module.xml;  I'll have a look.

**Comment by Sanne** [comment]
Fixed it. Preparing to release this.. thanks again!

**Pull request closed without merging**
