### PR TITLE
Feature packs

### PR DESCRIPTION
**Pull request by yrodiere**
@Sanne In case you want to check it... Otherwise I'll merge.

### CODE REVIEW

**Comment by Sanne** [comment]
thanks, having a quick look..

**Comment by Sanne** [comment]
it's not rebased?

**Comment by Sanne** [comment]
Looks good. very minor thing, you could include e9c48f50dd0a5858bcc1aa5db036af9c8deb46b6 but it's entirely optional.

**Comment by yrodiere** [comment]
Applied your suggestion and merged, thanks!

**Pull request merged**
